name: Nitter Feed

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4hrs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch RSS Feed
        run: |
          wget -u "Mozilla/5.0" -O nitter-mappletons.xml https://nitter.poast.org/Mappletons/rss

      - name: Commit Changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add *.xml
          git commit -m 'Update Nitter feeds'
          git push

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
